version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(levelname)s: %(message)s"
  detailed:
    format: "[%(asctime)s] [%(levelname)s | %(module)s | Thread: %(threadName)s | Line %(lineno)d]: %(message)s"
    datefmt: "%Y-%m-%d T%H:%M:%S%z"

handlers:
  stdout:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: "ext://sys.stdout"

  log_file:
    class: logging.handlers.RotatingFileHandler
    filename: "logs/main_log.log"
    mode: "w"
    formatter: detailed
    level: DEBUG
    maxBytes: 10_000_000
    backupCount: 3

loggers:
  root:
    level: "DEBUG"
    handlers: [ stdout, log_file ]
